#' Package {bayessource}
#'
#' Bayesian approach to evaluate whether two sets of multivariate observations come from the same source.
#'
#' The observations are assumed to be generated by a hierarchical Normal-Inverted Wishart distribution.
#' The hyperparameters can be fitted using additional background data, covering samples from multiple sources.
#'
#' The package implements a Gibbs sampler to sample from the posteriors, and the computation of the marginal likelihood follows Chib (1995).
#' The Bayes factor can also be computed as a ratio of two marginal likelihoods.
#'
#' @docType package
#' @family core functions
#' @name bayessource-package
#' @import coda
#' @importFrom Rcpp evalCpp
#' @importFrom Rdpack reprompt
#' @useDynLib bayessource
#' @template gaussmv_model
#' @references \insertAllCited{}
NULL
